### ISSUE TITLE
Active bar files list only prints top level titles

### ISSUE THREAD

**Issue by pixelpicosean** [fabiospampinato/vscode-todo-plus#138] opened 2018-10-15 23:23 UTC

**Comment by pixelpicosean** [comment] 2018-10-15 23:28
I did not change any settings, and any folder with a `TODO` file gives the same result:

![screenshot](https://cl.ly/b8a93affd80d/Image%202018-10-16%20at%207.27.05%20AM.png)

**Comment by fabiospampinato** [comment] 2018-10-15 23:28
Can you post the actual file so that I can try that myself?

**Comment by fabiospampinato** [comment] 2018-10-15 23:29
I see there's also a problem in the "Embedded view" 🤔 that message shouldn't be nested into an empty entry.

**Comment by pixelpicosean** [comment] 2018-10-15 23:32
Here's the [sample file](https://gist.github.com/pixelpicosean/ef1000abc05ec8513e07ea2cdf36e75d)

**Comment by fabiospampinato** [comment] 2018-10-15 23:37
Thank you! I can reproduce both problems, I'll probably fix this tomorrow.

**Comment by fabiospampinato** [comment] 2018-10-16 00:54
> I see there's also a problem in the "Embedded view" 🤔 that message shouldn't be nested into an empty entry.

This is fixed in v4.8.6.

> Active bar files list only prints top level titles

This is actually kind of a problem with your settings, by default the indentation is set to 2 spaces:

```
"todo.indentation": "  "
```

While you are using a 4-spaces indentation here instead, so by putting this into your settings:

```
"todo.indentation": "    "
```

Everything should work for you. But this is kind of a problem because then one wouldn't be able to edit both todo files indented with 2 spaces and todo files indented with 4 spaces, so I'm keeping this open, I'll try to find a smarter solution to this.

**Comment by fabiospampinato** [comment] 2018-10-16 21:44
This should be fixed in v4.9.0.

The extension is now detecting the indentation on a per-file basis.

**Closed by fabiospampinato** 2018-10-16 21:44 UTC
Labels: bug
