### ISSUE TITLE
add a "todo.colors.created" setting

### ISSUE THREAD

**Issue by Quentigus** [fabiospampinato/vscode-todo-plus#73] opened 2018-06-14 13:59 UTC
Please add an "todo.colors.created"  setting to allow customisation avec the @created tag
Thanks

**Comment by fabiospampinato** [comment] 2018-06-14 14:00
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/33.

**Closed by fabiospampinato** 2018-06-14 14:00 UTC
