### ISSUE TITLE
Global Todo file as input

### ISSUE THREAD

**Issue by Vanthiyadevan** [fabiospampinato/vscode-todo-plus#125] opened 2018-09-18 08:08 UTC
Currently this extenstion creates `TODO` files inside every folder/project. Is there is a way to open a global todo file ? I see there is no options in the settings now. 

Setting to supply file path would be nice.

**Comment by fabiospampinato** [comment] 2018-09-19 10:00
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/78.

**Closed by fabiospampinato** 2018-09-19 10:00 UTC
