### ISSUE TITLE
Archive only if sub-tasks are completed

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#42] opened 2018-04-05 15:45 UTC
When I press archive, I only want top level tasks with no incomplete nested tasks to be sent to the archive section with indentation preserved.

For example:

- Task 1 @done
    - Subtask 1 @done
    Note 1
    - Subtask 2 @done
- Task 2 @done
    - Subtask 1 @done
    - Subtask 2
- Task 3

When archive is pressed, I should see the following

- Task 2 @done
    - Subtask 1 @done
    - Subtask 2
- Task 3

Archive:
- Task 1 @done
    - Subtask 1 @done
    Note 1
    - Subtask 2 @done

**Comment by fabiospampinato** [comment] 2018-04-07 11:52
Checking for uncompleted todos should be doable, I'll be happy to consider a PR for this.

I think preserving the indentation would be non-trivial, since there might be multiple projects with the same name and we'll have to merge them somehow.

**Comment by fabiospampinato** [comment] 2018-04-27 19:07
Duplicate of #25 regarding preserving indentation.

Won't fix the other issue as you shouldn't mark tasks as completed if they have uncompleted sub-tasks.

**Closed by fabiospampinato** 2018-04-27 19:07 UTC
Labels: wontfix
