### ISSUE TITLE
done symbol color does not change in vscode 1.24

### ISSUE THREAD

**Issue by fabysdev** [fabiospampinato/vscode-todo-plus#69] opened 2018-06-07 07:17 UTC
Hi.

The done symbol does not change the color in vscode 1.24

Config:
```
  "todo.colors.done": "#949494",
  "todo.colors.cancelled": "#949494"
```

TODOs:
```
Test:
    ✔ TODO 1 @done(18-06-07 09:12)
    ✘ TODO 2 @cancelled(18-06-07 09:12)
    ☐ TODO 3
```

Output:
![image](https://user-images.githubusercontent.com/2088490/41084056-59ce99fc-6a33-11e8-847f-192da15d118d.png)

**Comment by samael205** [comment] 2018-06-07 09:31
Like this
And I have not modified that configuration
![todoerror](https://user-images.githubusercontent.com/649740/41091119-253851f2-6a46-11e8-8157-48671f7f3420.jpg)

**Comment by fabiospampinato** [comment] 2018-06-07 09:32
@samael205 what's the problem exactly, does the "✔" look different now?

**Comment by samael205** [comment] 2018-06-07 09:34
@fabiospampinato Exactly, it does not look like the first time I installed it. It's silly, but I do not understand why this has changed me

**Comment by fabiospampinato** [comment] 2018-06-07 09:35
@samael205 I have no clue. We certainly didn't change anything. Are you on Windows?

**Comment by samael205** [comment] 2018-06-07 09:38
Yes, @fabiospampinato You can pass me the done icon that appears in the gifs of the repository, to see if establishing it, changes?

**Comment by fabiospampinato** [comment] 2018-06-07 09:44
@samael205 I just pasted it here a few messages earlier. You can also get it from the readme.

**Comment by samael205** [comment] 2018-06-07 09:53
> Did the "done" symbol look like that before for you?
Yes,  In relation to the question that, yes, it looked like this before, and it looks now as you see it in the screenshot

**Comment by fabysdev** [comment] 2018-06-07 09:54
@fabiospampinato did you change the color settings?  Looks like you did not because the text is also green.

Maybe it is a windows problem, because i am also seeing the change @samael205  mentioned. It seems like the done symbol is wider now.

**Comment by fabiospampinato** [comment] 2018-06-07 09:56
@fabysdev I didn't push any update recently. It also looks like a Windows problem to me, I don't have it on macOS. I see from your screenshot that done/cancelled todos are not properly colored either, this is probably a bug of the extension, but I can't reproduce it.

**Comment by fabysdev** [comment] 2018-06-07 10:00
@fabiospampinato Cancelled looks correct in my screenshot, i changed the color ` "todo.colors.cancelled": "#949494"`. The text color of the done is also correct, because of` `"todo.colors.done": "#949494",`. Only the symbol is forced to green.

I assume there was a change in the vscode theme in 1.24 on windows. because the symbol is also green in the settings. Maybe there is a way to force the color on the symbol ?

![image](https://user-images.githubusercontent.com/2088490/41092948-601e5d3a-6a4a-11e8-9523-cbaabd70def7.png)

**Comment by fabiospampinato** [comment] 2018-06-07 10:14
> I assume there was a change in the vscode theme in 1.24 on windows. 

Yeah I think so, I've opened an issue about that https://github.com/Microsoft/vscode/issues/51335.

> Maybe there is a way to force the color on the symbol ?

That's what we are doing for making it green, VSC is just ignoring our decorations or something.

**Comment by fabysdev** [comment] 2018-06-07 10:15
@fabiospampinato  Thanks. It is just that specific symbol.

The other check symbol  "✓" works.

**Comment by fabiospampinato** [comment] 2018-06-12 10:50
They have reverted the commit that caused the problem, this will be fixed in the next release. https://github.com/Microsoft/vscode/issues/51335

**Closed by fabiospampinato** 2018-06-12 10:50 UTC
Labels: bug, upstream

**Comment by samael205** [comment] 2018-06-12 13:21
Thanks
