### ISSUE TITLE
Filtering by Tag

### ISSUE THREAD

**Issue by jadiaz** [fabiospampinato/vscode-todo-plus#18] opened 2017-11-05 18:22 UTC
Would like to be able to view all todo's by tag

**Comment by fabiospampinato** [comment] 2017-11-05 18:26
You mean the way PlainTasks does it?

**Comment by jadiaz** [comment] 2017-11-05 18:29
Yes. Being able to work on similarly tagged tasks is essential.

**Comment by fabiospampinato** [comment] 2017-11-05 18:37
I'd like to implement it, but I believe there's no API for doing that at the moment. 

I've opened an [issue](https://github.com/Microsoft/vscode/issues/37682) on VSC's repository, it would be helpful if you give it a thumbs up or write something.

**Comment by fabiospampinato** [comment] 2018-08-09 19:51
It's still impossible to properly implement this, but as of v3 this extension contributes a view to the activity bar that can be filtered by any arbitrary string. 👍

**Comment by fabiospampinato** [comment] 2018-11-06 14:55
@maiph you can do that, but then if you edit those todos the original file won't change. I'd prefer to implement this properly as soon as an API for folding arbitrary lines is available.

**Comment by SuperCuber** [comment] 2019-03-01 15:00
Is there a way to implement it using window similar to `Ctrl+Shift+F`? It could have a superset of the functionality, but also stuff like filtering by due date (#23). Each line in the result would correspond to an unticked checkbox (or maybe have that an option - `only show uncompleted tasks`) and clicking on that line would send you to that todo in the appropriate file.

That window could also have sorting by priority and similar features.

**Comment by fabiospampinato** [comment] 2019-03-01 15:08
@SuperCuber Yeah I guess one could ask for the search query via a quickpick panel and then open a new editor with the results.

**Comment by SuperCuber** [comment] 2019-03-01 15:50
I was thinking something along the lines of [this](https://owo.whats-th.is/KxHC4QR.png) (screenshot from Zim Wiki's Manual)

You can see on the left it shows priority level (one `!` for each level) and start/due time (OD stands for overdue since the docs are pretty old), and on the right the text. Clicking on the task just selects the text of the task in the appropriate page/line [like so](https://owo.whats-th.is/4rNSEUL.png). At the bottom (not shown) there is a textbox where you can enter a query.
Editing through that is simply not supported, to edit you need to click on the task.

IMO it's very intuitive and useful, especially if you can input stuff like `est < 2h && due < 2019-03-01 && priority > high`, and most important - doesn't require any folding.

**Comment by fabiospampinato** [comment] 2019-12-24 14:48
Now there might be the necessary APIs for implementing this 🤔 I'll have to take a closer look at it

**Comment by fabiospampinato** [comment] 2021-04-02 21:11
Closing as duplicate of #85

**Closed by fabiospampinato** 2021-04-02 21:11 UTC
Labels: enhancement, missing api
