### ISSUE TITLE
Archived items should retain parent project

### ISSUE THREAD

**Issue by JohnBarkerPG** [fabiospampinato/vscode-todo-plus#80] opened 2018-07-10 15:20 UTC
I think items moved to the archive section should retain the parent project that they were originally assigned to.

At the moment, you end up losing some context when items are moved to the archive as they end up in a flat list.

**Comment by fabiospampinato** [comment] 2018-07-10 15:44
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/25.

**Closed by fabiospampinato** 2018-07-10 15:45 UTC
