### ISSUE TITLE
Moving task with subtasks with ALT + Up/Down messes with indentation

### ISSUE THREAD

**Issue by Roodey86** [fabiospampinato/vscode-todo-plus#231] opened 2019-10-29 10:05 UTC
Hi Fabio,

Awesome extension. Only thing that bothers me is that if you move nested tasks (task > subtasks structure) with ALT + Up or ALT + Down the indentation gets messed up.
Can you look into this?
Thanks in advance.

**Comment by fabiospampinato** [comment] 2019-10-29 10:25
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/113

**Closed by fabiospampinato** 2019-10-29 10:25 UTC
