### ISSUE TITLE
Extension doesn't work with VSCode 1.16

### ISSUE THREAD

**Issue by axefrog** [fabiospampinato/vscode-todo-plus#5] opened 2017-09-11 21:56 UTC
I have a standard release of VSCode open with my project folder loaded. There is a .vscode folder in the root, a node_modules folder and a number of other folders as per any standard JavaScript project.

When I try to use the command to open my todo file, I get an error saying that I need to have a project open in order to use the extension. What does this even mean? I do have a project open. Are you perhaps testing on the insiders build, which has the multiroot workspace stuff included? Or is there something else going on?

**Comment by fabiospampinato** [comment] 2017-09-20 20:27
The API required for the multi-root functionalities, which this extension uses, is actually available since v1.15, are you running some older version?

This might be a duplicate of #6, read my response to that. Is that the case here?

**Comment by fabiospampinato** [comment] 2017-09-24 20:17
Should be fixed on v1.5.0. Closing as duplicate of #7.

**Closed by fabiospampinato** 2017-09-24 20:17 UTC

**Comment by honkskillet** [comment] 2018-05-04 03:02
I'm still getting this error.  Just installed todo+.  VSCODE 1.23.0 and TODO+ 1.10.7
"You have to open a project before being able to open its todo file"

**Comment by fabiospampinato** [comment] 2018-05-04 03:05
@honkskillet did you have any folder open when you executed the command? Did you have the focus on a file contained inside that folder or maybe something else (i.e. VSC settings)?

**Comment by honkskillet** [comment] 2018-05-04 03:07
Ah, that was it.  I had the todo+ setting as my focus.
Thank you for the  quick reply.

**Comment by fabiospampinato** [comment] 2018-05-04 03:12
@honkskillet no problem.
