### ISSUE TITLE
[Improvement] New Status (In Progress/Doing, Postponed, Won't Do/Unecessary)

### ISSUE THREAD

**Issue by neomacedo** [fabiospampinato/vscode-todo-plus#76] opened 2018-06-20 19:33 UTC
Will be great to have these new Status:

In Progress / Doing
Postponed
Won't Do / Unecessary

**Comment by fabiospampinato** [comment] 2018-06-20 22:03
I'm closing this as a duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/59 as the latter is more general.

**Closed by fabiospampinato** 2018-06-20 22:03 UTC
