### ISSUE TITLE
Potential Improvement: Darker syntax highlight colors for light themes

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#204] opened 2019-06-07 14:11 UTC
The syntax highlighting for todo-plus taskpaper documents looks great in dark theme. Colors selected for most light themes I have tried are too bright, with very little contrast, as shown below. Improvements to this would be much appreciated.

![image](https://user-images.githubusercontent.com/6100774/59110119-61817e00-890c-11e9-834b-205cbe6783d4.png)

**Comment by fabiospampinato** [comment] 2019-06-10 13:01
This is unimplementable currently: https://github.com/microsoft/vscode/issues/32813

We could pick some default colors for light themes, but IMHO those would never look perfect until the linked issue gets addressed.

Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/21.

**Closed by fabiospampinato** 2019-06-10 13:01 UTC
