### ISSUE TITLE
Archived tasks should keep its place in project structure 

### ISSUE THREAD

**Issue by WilliamStone** [fabiospampinato/vscode-todo-plus#71] opened 2018-06-12 13:43 UTC
Currently when archiving, completed tasks will be moved to Archive section, which is a plain list, making archived tasks lose their project information. Though it can be configured to generate @project tag, it is hard to review relationships among tasks.
I wonder if it's possible to retain project structure while moving completed tasks to Archive section like this:

//---------------- Original TODO file -------------
<pre>
projectA:
  projectA1:
    + Done task
    - todo task
  projectA2:
    + Done task2
projectB:
  projectB1:
    + Done task3
    - todo task2
</pre>

//---------------- TODO file after archive -------------

<pre>
projectA:
  projectA2:
    -todo task
projectB:
  projectB1:
    - todo task2

Archive:
  projectA:
    projectA1:
      + Done task
  projectB:
    projectB1:
      + Done task2
</pre>

The idea is inserting done task into Archive project tree by its project structure. I think this will make archived tasks better reviewable.

**Comment by fabiospampinato** [comment] 2018-06-12 13:44
Duplicate of https://github.com/fabiospampinato/vscode-todo-plus/issues/25.

**Closed by fabiospampinato** 2018-06-12 13:44 UTC
