### ISSUE TITLE
Possible Bug: Inconsisten Indenting Behavior below Project

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-todo-plus#226] opened 2019-09-16 18:22 UTC
When I press Alt-up to move the second task right below a project, sometimes it is at the same level as the project or indented one level to the project:

Example

Project:
    - Task 1
    - Task 2

When I press alt-up, I end up with either

Case 1
-------

```
Project:
-Task 2
    - Taske 1
```

or 

Case 2
-------
```
Project:
    - Task 2
    - Task 1
```

I Prefer Case 2 over Case 1 as the expected behavior.

**Comment by fabiospampinato** [comment] 2019-09-16 18:41
I think this is a duplicate of https://github.com/microsoft/vscode/issues/57197

**Closed by fabiospampinato** 2019-09-16 18:41 UTC

**Comment by sahil48** [comment] 2019-09-16 19:00
That was the exact gif wanted to record! 😄

What do you use to make gifs like that?

**Comment by fabiospampinato** [comment] 2019-09-16 19:02
I think I used [kap](https://getkap.co/) for that 👍
