### ISSUE TITLE
'@file://' link for "js" files goes to new line on "Todo: Open Embedded" while not for "php" files

### ISSUE THREAD

**Issue by mrquantos** [fabiospampinato/vscode-todo-plus#84] opened 2018-07-21 15:20 UTC
Hi, Thank you for creating this awesome extension

Currently, I am facing a bug, that the TODOs generated from "Todo: Open Embedded" command are not formatted correctly for **"js"** files. TODOs generated from **"js"** files contains **'\n'** at the end of TODO "line" but this bug isn't present in other files (I only checked for **"php"** files). 

Anyway, I found out that changing **"trimStart"** to **"trim"** function on line [src/utils/embedded.ts#L116](https://github.com/fabiospampinato/vscode-todo-plus/blob/d392af623b07ec0fdcd7afe9ee708fe2fdf09f75/src/utils/embedded.ts#L116) fixes this problem.

```typeLines.push ( `${indentation}${groupByFile ? indentation : ''}${box} ${_.trimStart ( line )} @file://${encodedFilePath}#${lineNr + 1}` );```

to 

```typeLines.push ( `${indentation}${groupByFile ? indentation : ''}${box} ${_.trim ( line )} @file://${encodedFilePath}#${lineNr + 1}` );```

Is this the intended behaviour?

**Comment by quantos-unios** [comment] 2018-07-21 17:55
@fabiospampinato Ok here is "Todo: Open Embedded" output with **trimStart** function

![screenshot from 2018-07-21 22-46-29](https://user-images.githubusercontent.com/18618510/43038722-61c204e6-8d38-11e8-9194-51c5aa2ab121.png)

and following output is with **trim** function

![screenshot from 2018-07-21 22-43-01](https://user-images.githubusercontent.com/18618510/43038749-c457ad36-8d38-11e8-8253-061d73b56e5a.png)

**Comment by fabiospampinato** [comment] 2018-07-21 20:10
@quantos-unios I see the problem, but I don't understand why this happens, [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/d392af623b07ec0fdcd7afe9ee708fe2fdf09f75/src/utils/embedded.ts#L61) we should be affectively stripping out newline characters 🤔. 

Could you post here an actual file that causes this problem for you? I'll have to reproduce it to understand it.

**Comment by quantos-unios** [comment] 2018-07-21 21:13
@fabiospampinato Ok I have attached the two files "main.js" which have this issue and "TeacherController.php" file which doesn't have this issue, also screenshots of output are included with **"trimStart"** function and **"trim"** function. 

However, I have removed the actual code from files because I do not own it and it is proprietary but the bug is still reproducible here.

[tp-issue.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/2216502/tp-issue.zip)

**Comment by quantos-unios** [comment] 2018-07-22 08:18
@fabiospampinato I have removed all empty lines from "main.js" and "TeacherController.php" and console logged output of [lines](https://github.com/fabiospampinato/vscode-todo-plus/blob/d392af623b07ec0fdcd7afe9ee708fe2fdf09f75/src/utils/embedded.ts#L61) next to the line and copied the output to vs-code for both "main.js" and "TeacherContorller.php". Here is what I did

![screenshot from 2018-07-22 12-45-08](https://user-images.githubusercontent.com/18618510/43043510-c8fe02ec-8dae-11e8-8580-d7646a37f6e1.png)

![screenshot from 2018-07-22 12-45-52](https://user-images.githubusercontent.com/18618510/43043512-d1a7dcec-8dae-11e8-8e7d-13659ca06cef.png)

![screenshot from 2018-07-22 11-46-44](https://user-images.githubusercontent.com/18618510/43043103-0530e6d0-8da5-11e8-8bd6-142aa7f6ebc0.png)

Here is the console log for **"main.js"**

![screenshot from 2018-07-22 12-47-45](https://user-images.githubusercontent.com/18618510/43043517-dfea29a4-8dae-11e8-9f1a-3ee8d99ff117.png)

I have copied log from console and saved in a file, it can be seen that **"lines"** contains a **'\n'** before **"** character for all TODOs, I have also checked **"lines"** log output in hex editor and it contains a **'LF'** character with hex **'0A'** before ending **"** character.
 
![screenshot from 2018-07-22 12-49-36](https://user-images.githubusercontent.com/18618510/43043533-1ade1b56-8daf-11e8-8e97-6bffa5bc0cf5.png)

Here is the lines log for **"main.js"** in hex editor

![screenshot from 2018-07-22 12-53-53](https://user-images.githubusercontent.com/18618510/43043577-fd706dac-8daf-11e8-9060-bee0a8b2eb44.png)

but the **"lines"** log output for **"TeacherController.php"** does not contain a **'\n'** character before ending **"** character as can be seen from following screenshot.

![screenshot from 2018-07-22 12-52-29](https://user-images.githubusercontent.com/18618510/43043585-3ddf3d1e-8db0-11e8-8684-f5a5d382ef59.png)

Here is the zip file containing "main.js" and "TeacherController.php" with empty lines removed and also screenshots are included

[tp-issue-log.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/2216817/tp-issue-log.zip)

**Comment by quantos-unios** [comment] 2018-07-22 08:41
Ok I think I have found the bug, it isn't a problem with "js" or "php". If you change file's line encoding to **"CRLF"** from **vs-code status bar** then this bug occurs while if line encoding is **"LF"** then it works fine on all files.

To reproduce bug change line encoding

![screenshot from 2018-07-22 13-37-54](https://user-images.githubusercontent.com/18618510/43043847-85f3a6c2-8db4-11e8-81fe-4ba29649ee7c.png)

to

![screenshot from 2018-07-22 13-31-25](https://user-images.githubusercontent.com/18618510/43043828-2ed8fcac-8db4-11e8-8aae-7be2de7d980c.png)

**Comment by fabiospampinato** [comment] 2018-07-22 16:16
Thanks for debugging this for me 😄I'll fix this as soon as I get enough free time, I suspect I might have to update a few other extensions of mine as well.

**Comment by quantos-unios** [comment] 2018-07-22 16:47
No problem. It was pleasure debugging it :smile:

**Comment by fabiospampinato** [comment] 2018-08-01 01:04
Fixed in v2.3.0. Thanks again for the help!

**Closed by fabiospampinato** 2018-08-01 01:04 UTC
Labels: bug
