### ISSUE TITLE
File view: not all *.todo files are detected

### ISSUE THREAD

**Issue by nilsml** [fabiospampinato/vscode-todo-plus#104] opened 2018-08-15 09:07 UTC
I have several *.todo-files in my workspace, but none is detected.
Tried renaming some of them to TODO and then they were picked up.

Ex: Project1.todo, Project2.todo

**Comment by rlundy** [comment] 2018-08-15 11:00
*.tasks files aren't detected either.

**Comment by fabiospampinato** [comment] 2018-08-15 11:34
> (...) but none is detected.
> *.tasks files aren't detected either.

What do you guys mean by "detected", are they not highlighted at all or is it something else?

> I have several *.todo-files in my workspace, but none is detected.

Is that extension used by any even mildly popular app or is that something you decided on using?

**Comment by nilsml** [comment] 2018-08-15 12:05
In the activity bar when selecting the Todo view, the File-section does not show any detected todo-files.
The documentation states that files with *.todo should be supported:

>  "TODO", // Todo file name. Other supported names are: `*.todo`, `*.todos`, `*.task`, `*.tasks`, `*.taskpaper` and `todolist.txt`

The syntax highlighting works though.

**Comment by nealot** [comment] 2018-08-15 16:33
I can confirm that the "*" quantifier is not working as intended.

This also raises another issue: What happens when there are multiple *.todo files in the root directory?

**Comment by fabiospampinato** [comment] 2018-08-15 17:44
I get what you guys mean now, the hyphen in `*.todo-files` got me confused, I thought @nilsml was giving a weird `.todo-files` extension to his todo files.

> "todo.file.name": "TODO", // Todo file name. Other supported names are: *.todo, *.todos, *.task, *.tasks, *.taskpaper and todolist.txt

That line means that all files whose names match those pattern are properly highlighted.

> In the activity bar when selecting the Todo view, the File-section does not show any detected todo-files.

> This also raises another issue: What happens when there are multiple *.todo files in the root directory?

That's now how it works, it currently only looks for the file defined in your `todo.file.name` setting, all other files are ignored. In fact the view is called `File`, not `Files`.

I also think all todo files should be shown there, the initial release of the feature just didn't support that.

**Comment by fabiospampinato** [comment] 2018-08-17 22:53
Added multi-root and multi-file support in v4.2.0 👍 

The icons should be fixed in VSC v1.27 (I think) https://github.com/Microsoft/vscode/issues/56143

**Closed by fabiospampinato** 2018-08-17 22:53 UTC
Labels: enhancement
