### ISSUE TITLE
Error in new versions of VSCode

### ISSUE THREAD

**Issue by Nick-Hopps** [fabiospampinato/vscode-todo-plus#275] opened 2020-07-16 16:05 UTC
[fabiospampinato.vscode-todo-plus]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api fabiospampinato.vscode-todo-plus

**Comment by fabiospampinato** [comment] 2020-07-16 16:09
Duplicate of https://github.com/microsoft/vscode/issues/102170#issuecomment-658041160

I think they fixed it already.

**Closed by fabiospampinato** 2020-07-16 16:09 UTC
