### ISSUE TITLE
Feat req - Toggle doubt regarding completion

### ISSUE THREAD

**Issue by shahul01** [fabiospampinato/vscode-todo-plus#349] opened 2022-02-10 13:48 UTC
one might not be clear whether some todos are done or cancelled, these todos should have orange color and should be followed by (?) or *, next to check mark or cross.

This helps in coming back to them at later time to confirm whether they are done.

**Comment by fabiospampinato** [comment] 2022-02-16 05:36
Duplicate of #323. It's not clear when/why a task would be in an indeterminate state though 🤔 like does it start indeterminate? is it possible to determine if it's actually done or not if one spent time on it?

**Closed by fabiospampinato** 2022-02-16 05:36 UTC

**Comment by shahul01** [comment] 2022-02-16 09:07
say I fixed a bug but I have no way of checking it till I fix a related bug, I would like to mark it but check it again to make sure its fixed...
