### ISSUE TITLE
[Enchancement] Filter tasks by tag

### ISSUE THREAD

**Issue by samael205** [fabiospampinato/vscode-todo-plus#30] opened 2018-02-07 08:43 UTC
Hello,

I would like to make a suggestion.

Could you create a command, in which you would put for example filter> @done: 18-02-06 and that only the tasks completed for that day would appear?

What I'm saying is making a command filter by tag.

**Comment by fabiospampinato** [comment] 2018-02-07 19:39
I'm closing this as a duplicate of [another issue](https://github.com/fabiospampinato/vscode-todo-plus/issues/18).

There's currently no way to implement this the way PlainTasks does it, for the time being you'll have to just search for your tags (basically `ctrl+f` -> `@done`).

**Closed by fabiospampinato** 2018-02-07 19:39 UTC
