### ISSUE TITLE
Keystroke lag with projects

### ISSUE THREAD

**Issue by IAmFletcher** [fabiospampinato/vscode-todo-plus#210] opened 2019-07-17 08:06 UTC
**VS Code:** 1.36.1-1
**Todo+:** 4.13.0

Had the same issue as #53 on a fresh Manjaro Linux install in a 100 line file. 

Looked at Process Explorer and was jumping to between 2% and 11% CPU on a single toggle box, and stayed between 8% to 12% when continuously toggling box.

With statistics disabled, I was jumping to between 1-2% on a single toggle box, and remained stable at 5% when continuously toggling box. There was also no more noticeable keystroke lag.

It seems to be related to projects specifically. 100 tasks on a new file was fine, but 16 projects and 84 tasks produced the issues listed above. It also doesn't seem to matter if they're nested, or not.

Tried on the latest Insiders (1563341490-1), and performance improved by about 2-3% whether statistics was enabled, or not. There was also less keystroke lag with statistics enabled, although it was still noticeable.

**Comment by fabiospampinato** [comment] 2019-07-17 19:05
I'm closing this as a duplicate of #54.

Unfortunately we are pretty limited by the APIs provided by VSCode, writing a performant dynamic syntax highlighter like ours gets pretty complicated when dealing with those. If you have more ideas on how to help improve the situation I'm all ears.

**Comment by squidfunk** [comment] 2019-07-22 19:24
I'm having the same problem. Specifically the more edits I make to the TODO file after I open VS Code, the slower and slower it gets. Adding a simple space will make the CPU jump to 70-80%. My current solution is to close VS Code and reopen it, but I've been doing this for months now and is really annoying.

**Comment by fabiospampinato** [comment] 2019-07-22 19:36
@squidfunk Wait does reloading the window fix the problem for you? If so we might have some kind of memory leak or something. It also also be something happening at the vscode-level that we have no control over.

**Comment by squidfunk** [comment] 2019-07-23 07:20
Here's a gif showing the severe lag. Reloading does not solve the problem.

![Ohne Titel](https://user-images.githubusercontent.com/932156/61690996-daa52b00-ad2a-11e9-8459-4d7b6dae9d92.gif)

**Comment by squidfunk** [comment] 2019-07-23 07:33
Here's another recording that hints that syntax highlighting is probably triggered on every keystroked and chained together. It takes a long time until the highlighter catches up.

![OhneTitel](https://user-images.githubusercontent.com/932156/61691930-edb8fa80-ad2c-11e9-9bbc-9da2c2860eda.gif)

**Comment by squidfunk** [comment] 2019-07-23 08:00
I tested the `projects` regex from here on [regex101.com](https://regex101.com/) with my file – it had more than 10k steps. However, the projects regex is only a singular regex, so I guess the sum of regexes makes it feel very, very slow.

https://github.com/fabiospampinato/vscode-todo-plus/blob/ad223abe4c48fbf5eef02d3dce75fd1bd2d399f6/src/consts.ts#L42-L71

I played a little around with the regex and could cut step count in half by just replacing the `(.+:)` in the middle with `([^:\n]+:)`, as the former will lead to excessive backtracking. When I cut down the regex to `^[^\S\n]*([^:\n]+:)`, which also has some false positives like tasks with colons in them, I get the matching time down to 3k steps. In my opinion this shows that the regex approach does not scale well.

On a side note: I've just implemented a CSS parser and first used a lot of regular expressions. It was insanely slow and also wrong, as CSS is not a regular grammar. Then, following a tokenization-based approach as described by the official specs, I managed to improve performance by a factor of 20-40, depending on the input. Parsing time now also scales linearly with input size. I would recommend refactoring the regular expressions by using a parser generator. My testing has shown that [Chevrotain](https://github.com/SAP/chevrotain) is very fast and easy to work with.

**Comment by fabiospampinato** [comment] 2019-07-23 12:40
@squidfunk 

- Can you check if you can still reproduce the issue in VSCode Insiders with only Todo+ installed?
- If you can, can you send me a file that reproduces the problem?
- I see from your screencasts that your tasks are being rendered in italic, that doesn't look right to me, what's up with that?
- I agree that a real parser/tokenizer would deal better performances, but here the biggest issue is that we are re-decorating the entire thing most of the times, VSCode's APIs are pretty limiting in this regard. Perhaps there's a way to cache decorations for untouched lines though, I haven't explored this area yet.

**Comment by squidfunk** [comment] 2019-07-23 14:05
> * Can you check if you can still reproduce the issue in VSCode Insiders with only Todo+ installed?

Will need to install insiders first, but it's probably related to the extension itself.

> * If you can, can you send me a file that reproduces the problem?

I will try to create a reproducible case.

> * I see from your screencasts that your tasks are being rendered in italic, that doesn't look right to me, what's up with that?

This has nothing to do with the extension or problem, it's just my font preference.

> * I agree that a real parser/tokenizer would deal better performances, but here the biggest issue is that we are re-decorating the entire thing most of the times, VSCode's APIs are pretty limiting in this regard. Perhaps there's a way to cache decorations for untouched lines though, I haven't explored this area yet.

It would probably be a great performance improvement only redecorating the changed line. The tokenization approach however will also be fast enough in case of permanent redecoration.

**Comment by fabiospampinato** [comment] 2019-07-23 14:11
> The tokenization approach however will also be fast enough in case of permanent redecoration.

I'm not sure that's actually the bottleneck here, I've been editing a 10k lines `.todo` file without too much of a struggle, and that's surely an unrealistic file size, your ~100 lines files should be handled just fine, there's probably another issue here besides regexes.

**Comment by fabiospampinato** [comment] 2019-07-23 14:13
> This reproduces it for me:

I can't feel any junkiness editing that file. Try using the extension in a fresh VSCode installation, perhaps there's a conflict with some other extension.

**Comment by squidfunk** [comment] 2019-07-23 14:58
I just tested with a fresh VS Code insiders installation. The only thing installed is Todo+:

https://imgur.com/a/Fw3sVpB

Exactly the same result.

**Comment by fabiospampinato** [comment] 2019-07-23 15:02
I'm reopening as it seems clear that there's an addressable issue here, the issue is that I'm unable to reproduce it

**Comment by fabiospampinato** [comment] 2019-07-23 15:03
I'm reopening as it seems clear that there's an addressable issue here, but unfortunately I'm unable to reproduce it.

You will have to try to debug this yourself I'm afraid.

**Comment by squidfunk** [comment] 2019-07-23 15:08
> You will have to try to debug this yourself I'm afraid.

Any directions on it? Happy to help. Is there an easy way to profile the highlighting, ideally to create a flame graph?

**Comment by fabiospampinato** [comment] 2019-07-23 15:22
Read [this](https://github.com/fabiospampinato/vscode-todo-plus#contributing), then run `Debug Launcher: Auto`.

A flame graph would be nice, unfortunately by debugging the extension VSCode's debugger is being attached, which doesn't provide the ability to record a flame graph as far as I know. 

I'd say check how long the functions [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Ftodo%2Fdecorators%2Fdocument.ts/#L159) and [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Ftodo%2Fdecorators%2Fdocument.ts/#L174) take. And check how many times the decorations are being [updated](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Ftodo%2Fdecorators%2Fdocument.ts/#L65-L66), if that's more than once per keystroke we might have a problem.

**Comment by squidfunk** [comment] 2019-07-23 15:22
[Found it](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions). Here is a fresh CPU profile:

[CPU-20190723T151847.077Z.cpuprofile.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/3422764/CPU-20190723T151847.077Z.cpuprofile.zip)

![Bildschirmfoto 2019-07-23 um 17 21 58](https://user-images.githubusercontent.com/932156/61724502-62f8ef80-ad6e-11e9-83f2-e6f7a23ae50b.png)

**Comment by fabiospampinato** [comment] 2019-07-23 15:23
Oh nice, I didn't even know that was possible.

**Comment by fabiospampinato** [comment] 2019-07-23 15:23
Is all that taking place for a single keypress?

**Comment by squidfunk** [comment] 2019-07-23 15:24
No, that is basically the same thing I did for the latest imgur video, i.e. extending a code block with further characters.

**Comment by fabiospampinato** [comment] 2019-07-23 15:25
I'd be useful if you can export that (right click on the profile -> save...) so that I can import that on my end. Or I guess I'll set this up myself, but I've been pretty busy with other projects of mine to dedicate a ton of time to this.

**Comment by squidfunk** [comment] 2019-07-23 15:27
I already attached the profile in the zip file with the screenshot. Here it is again:
[CPU-20190723T151847.077Z.cpuprofile.zip](https://github.com/fabiospampinato/vscode-todo-plus/files/3422764/CPU-20190723T151847.077Z.cpuprofile.zip)

**Comment by squidfunk** [comment] 2019-07-23 15:29
Oh another hint: when I just open the TODO file with file type Markdown, everything works perfect - no lag, no delay, everything is updated instantly.

**Comment by fabiospampinato** [comment] 2019-07-23 15:53
> I already attached the profile in the zip file with the screenshot.

Oh right, sorry!

I can totally reproduce this by doing the same thing you're doing in the screencast, previously I was just editing todos/projects or writing quickly.

We have an [optimization](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src%2Ftodo%2Fdecorators%2Fdocument.ts/#L119) where if a decoration between edits is supposed to change, say the length of the text to decorate changes, but in both cases it encompasses the entire line we just do nothing. It seems that this isn't actually working for your use case for some reason.

From the flame chart you provided I see lots of small things that could perhaps be optimized.

Ultimately though the definitive performance optimization would be to make the re-decoration process a `O(number of edited lines)` process rather than the currently `O(number of lines)` complexity in the general case. That's tricky to do because of VSCode's APIs, but there might be a way to do it.

> Oh another hint: when I just open the TODO file with file type Markdown, everything works perfect - no lag, no delay, everything is updated instantly.

Yeah but then you miss on Todo+'s syntax highlighting. 

The reason why Markdown's syntax highlighting is much more performant is because they are actually properly tokenizing things, via a `.tmLanguage` file. We can't provide a `.tmLanguage` file because some of our decorations depend on your configuration settings, so we can't just create a static `.tmLanguage` file.

**Comment by fabiospampinato** [comment] 2019-07-23 15:54
I'll probably be able to take a closer look at this during one of the following weekends. If you'd like to optimize things yourself though PRs are more than welcome 👍

**Comment by squidfunk** [comment] 2019-07-23 16:06
@fabiospampinato the reproduction (= hammering on the keyboard) was just to demonstrate the issue. The lagging mainly happens when I edit lines or move blocks of TODOs around, especially when I extend code blocks.

> Ultimately though the definitive performance optimization would be to make the re-decoration process a O(number of edited lines) process rather than the currently O(number of lines) complexity in the general case. That's tricky to do because of VSCode's APIs, but there might be a way to do it.

Fully agree. 

I'm an open source maintainer myself, so I know that time is a scarce resource. If you manage to find some time, it would be really great, but I understand that it might take a little. Nevertheless, I have to say: I love this extension. Thank you for creating and maintaining it!

**Comment by fabiospampinato** [comment] 2021-04-02 20:56
Closing in favor of #54

**Closed by fabiospampinato** 2021-04-02 20:56 UTC
Labels: bug, help wanted

**Comment by squidfunk** [comment] 2023-01-31 23:06
The problem was fixed in #367 and the fix was released in v4.19.1 🥳
