### ISSUE TITLE
Pausing of started tasks

### ISSUE THREAD

**Issue by stprograms** [fabiospampinato/vscode-todo-plus#317] opened 2021-04-19 12:45 UTC
Currently tasks can be started and when they are finished, they can be marked as done. The result is that the time between the __starting__ of the task and the marking of __done__ is also used for calculation of the __elapsed__ time. 
Tasks marked as __done__ cannot be started anymore.

It would be great if the possibility to pause a task could be implemented. Sadly interruptions occur in reallife where you have to work on a different task and interrupt your current work. This way, you could have a better timekeeping of what you have done.

Maybe this could be implemented by adding a `@paused` tag. So a completed task would have the tags `@started` `@done` `@elapsed` and `@paused`.

**Comment by arkadianriver** [comment] 2021-07-26 19:47
like these ideas: #88 ?

**Comment by fabiospampinato** [comment] 2022-02-16 05:25
Duplicate of #88

**Closed by fabiospampinato** 2022-02-16 05:25 UTC
